export const getInvoices="http://localhost:3001/Invoces"
export const getProducts="http://localhost:3001/Products"
export const getProduct="http://localhost:3001/Products/"
export const getClients="http://localhost:3001/Clients"
export const getmidprice="http://localhost:3001/Invoces/subtotal"
export const postInvoice="http://localhost:3001/Invoces"
